spring:
  application:
    name: jpa-hibernate-02-homework

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://my-postgres-postgresql.my-app-namespace.svc.cluster.local:5432/mydb}
    username: ${SPRING_DATASOURCE_USERNAME:myuser}
    password: ${SPRING_DATASOURCE_PASSWORD:mypassword}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
